name: sudoku
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  sudoku_api: ^2.1.0
  cupertino_icons: ^1.0.2
  animations: ^2.0.7
  timeago: ^3.3.0
  universal_io: ^2.0.4
  sprung: ^3.0.1
  flutter_spinkit: ^5.1.0
  phosphor_flutter: ^1.4.0
  enough_platform_widgets: ^0.5.0
  lottie: ^2.1.0
  qr_flutter: ^4.0.0
  flutter_fgbg: ^0.2.2
  font_awesome_flutter: ^10.3.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/animations/

  fonts:
    - family: Plus Jakarta
      fonts:
        - asset: "assets/fonts/Plus Jakarta/Extra Light.ttf"
          weight: 300
        - asset: "assets/fonts/Plus Jakarta/Extra Light Italic.ttf"
          weight: 300
          style: italic
        - asset: "assets/fonts/Plus Jakarta/Light.ttf"
          weight: 300
        - asset: "assets/fonts/Plus Jakarta/Light Italic.ttf"
          weight: 300
          style: italic
        - asset: "assets/fonts/Plus Jakarta/Regular.ttf"
          weight: 400
        - asset: "assets/fonts/Plus Jakarta/Italic.ttf"
          weight: 400
          style: italic
        - asset: "assets/fonts/Plus Jakarta/Medium.ttf"
          weight: 500
        - asset: "assets/fonts/Plus Jakarta/Medium Italic.ttf"
          weight: 500
          style: italic
        - asset: "assets/fonts/Plus Jakarta/Semi Bold.ttf"
          weight: 600
        - asset: "assets/fonts/Plus Jakarta/Semi Bold Italic.ttf"
          weight: 600
          style: italic
        - asset: "assets/fonts/Plus Jakarta/Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Plus Jakarta/Bold Italic.ttf"
          weight: 700
          style: italic
        - asset: "assets/fonts/Plus Jakarta/Extra Bold.ttf"
          weight: 800
        - asset: "assets/fonts/Plus Jakarta/Extra Bold Italic.ttf"
          weight: 800
          style: italic
    
    - family: Satoshi
      fonts:
        - asset: "assets/fonts/Satoshi/Light.ttf"
          weight: 300
        - asset: "assets/fonts/Satoshi/Light Italic.ttf"
          weight: 300
          style: italic
        - asset: "assets/fonts/Satoshi/Regular.ttf"
          weight: 400
        - asset: "assets/fonts/Satoshi/Italic.ttf"
          weight: 400
          style: italic
        - asset: "assets/fonts/Satoshi/Medium.ttf"
          weight: 500
        - asset: "assets/fonts/Satoshi/Medium Italic.ttf"
          weight: 500
          style: italic
        - asset: "assets/fonts/Satoshi/Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Satoshi/Bold Italic.ttf"
          weight: 700
          style: italic
        - asset: "assets/fonts/Satoshi/Black.ttf"
          weight: 800
        - asset: "assets/fonts/Satoshi/Black Italic.ttf"
          weight: 800
          style: italic

    - family: Telma
      fonts:
        - asset: "assets/fonts/Telma/Light.ttf"
          weight: 300
        - asset: "assets/fonts/Telma/Regular.ttf"
          weight: 400
        - asset: "assets/fonts/Telma/Medium.ttf"
          weight: 500
        - asset: "assets/fonts/Telma/Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Telma/Black.ttf"
          weight: 900